services:
  redis:
    image: redis:7-alpine
    restart: always
    container_name: redis
    command: ["redis-server", "--appendonly", "yes"]
    ports:
      - "6380:6379"
    volumes:
      - redis_data:/data

  redisinsight: 
    image: redis/redisinsight:latest
    container_name: redisinsight
    ports:
      - "5540:5540"
    depends_on:
      - redis
    volumes:
     - redisinsight_data:/data

volumes:
  redis_data:
  redisinsight_data:
